### DISCUSSION TITLE
jdeploy github action plugin not uploading to npm

### DISCUSSION THREAD

**Discussion by jpage4500** [shannah/jdeploy#146] [Q&A]
sorry last question -- I tried to use the GA plugin to send to npm and it didn't seem like anything happened. I didn't see an update in [npm](https://www.npmjs.com/package/android-device-manager?activeTab=versions)

```
      - name: Build App Installer Bundles
        uses: shannah/jdeploy@master
        with:
          github_token: ${{ github.token }}
          deploy_target: npm
          npm_token: ${{ secrets.NPM_TOKEN }}
```

Here's my github actions [script](https://github.com/jpage4500/AndroidDeviceManager/blob/develop/.github/workflows/jdeploy.yml#L38)

Here's the [results](https://github.com/jpage4500/AndroidDeviceManager/actions/runs/11407504505/job/31743661288)
