### DISCUSSION TITLE
Integrate jdeploy into github actions

### DISCUSSION THREAD

**Discussion by RouHim** [shannah/jdeploy#46] [Q&A] [answered]
Hi guys, I am currently trying to get jdeploy running in my github actions pipe. However, I am failing due to some very strange npm errors. Since I am not familiar with npm I wanted to ask if there is a reference implementation of jdeploy in github actions?

Thanks & greetings
Rouven

**Comment by shannah** [comment]
I don't have a reference implementation yet, but you might want to have a look at [this thread](https://github.com/shannah/jdeploy/issues/44), as it describes some of the steps.
You may also want to file an RFE for this in the issue tracker.

**Comment by RouHim** [comment]
Thanks, I already saw that topic, but was still not able to get my pipe running :(

My publish job looks like that:
```yaml
  publish:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Download jar from builder
        uses: actions/download-artifact@master
        with:
          name: discoverj-jar
          path: target
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          registry-url: 'https://registry.npmjs.org'
      - name: Install JDeploy
        run: npm install && npm install jdeploy
      - name: Set package version
        run: npm --no-git-tag-version version ${{ env.VERSION }}
      - name: JDeploy Publish
        run: ./node_modules/jdeploy/bin/jdeploy.js publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
```
