### ISSUE TITLE
Help with Github target_repository Build Fail

### ISSUE THREAD

**Issue by CrystalTours** [shannah/jdeploy#175]
Hello, i need some help, im struggling to get right the github publishing.

This is the jdeploy.yml

```
name: jDeploy CI with Maven

on:
  push:
    branches: [ 'master' ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'zulu'
          cache: maven
      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Build App Installer Bundles
        uses: shannah/jdeploy@master
        with:
          github_token: "HERE_I_PUT_THE_TOKEN"
          target_repository: 'CrystalTours/CTS-Releases'
```

My Original repo is private and the target is public
I make the commit/push and i got this error in the action build

![Image](https://github.com/user-attachments/assets/c743009f-fda2-4c37-9400-99e15ae9eca0)

I tried the github_token with Clasic token  and FineGrainded Tokens, for both repos with this settings:

- Contents -> read & Write
- Actions -> read & Write
- Administration -> read & Write
- WorkFlows -> read & Write

The link shows this

```
{
  "message": "Not Found",
  "documentation_url": "https://docs.github.com/rest/releases/releases#get-a-release",
  "status": "404"
}
```
Which says:
```
The fine-grained token must have the following permission set:

"Contents" repository permissions (read)
```

I dunno what im doing wrong! please help 
Thanks
